apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ordering-system
  description: End-to-end order flow from menu browsing to delivery
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: group:default/team-triple-d
  domain: customer-experience
